name: farmacias

services:
  oracle:
    image: gvenzl/oracle-free:23-slim     # Oracle 23ai/26ai Free, listo para desarrollo
    container_name: farmacias-oracle
    ports:
      - "1521:1521"                        # puerto_de_tu_PC : puerto_dentro_del_contenedor
    environment:
      ORACLE_PASSWORD: ${ORACLE_SYS_PASSWORD}   # toma el valor desde el archivo .env
    volumes:
      - oracle-data:/opt/oracle/oradata    # conserva los datos aunque borres el contenedor
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: farmacias-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver-data:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: farmacias-rabbitmq
    ports:
      - "5672:5672"     # puerto de mensajeria (por donde hablan los servicios)
      - "15672:15672"   # panel de administracion web (para ti, en el navegador)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  oracle-data:
  sqlserver-data:
  rabbitmq-data: